export const AppRoutes = {
  PANEL: "/panel",
  NOT_FOUND: `/404`,
  LOGIN: `/login`,
  ADMIN: `/admin`,
  ADD_BOOK_PRODUCT: `/admin/add-book-product`,
  ADD_BOOK_PRODUCT_ADDITIONAL_INFO: `/admin/add-book-product/additional-info`,
  ADD_BOOK_PRODUCT_DETAILD_INFO: `/admin/add-book-product/detaild-info`,
  ADD_BOOK_PRODUCT_MEDIA: `/admin/add-book-product/product-media`,
  ADD_AUDIOBOOK_PRODUCT: `/admin/add-audiobook-product`,
  ADD_AUDIOBOOK_PRODUCT_DETAILD_INFO: `/admin/add-audiobook-product/detaild-info`,
  ADD_AUDIOBOOK_PRODUCT_ADDITIONAL_INFO: `/admin/add-audiobook-product/additional-info`,
  ADD_AUDIOBOOK_PRODUCT_MEDIA: `/admin/add-audiobook-product/product-media`,
  ADD_VIDEOBOOK_PRODUCT: `/admin/add-video-product`,
  ADD_VIDEOBOOK_PRODUCT_ADDITIONAL_INFO: `/admin/add-videobook-product/additional-info`,
  ADD_VIDEOBOOK_PRODUCT_DETAILD_INFO: `/admin/add-videobook-product/detaild-info`,
  ADD_VIDEOBOOK_PRODUCT_MEDIA: `/admin/add-videobook-product/product-media`,
  ADD_MAGAZINE_PRODUCT: `/admin/add-magazine-product`,
  ADD_MAGAZINE_PRODUCT_ADDITIONAL_INFO: `/admin/add-magazine-product/additional-info`,
  ADD_MAGAZINE_PRODUCT_DETAILD_INFO: `/admin/add-magazine-product/detaild-info`,
  ADD_MAGAZINE_PRODUCT_MEDIA: `/admin/add-magazine-product/product-media`,
  ADD_EBOOK_PRODUCT: `/admin/add-ebook-product`,
  ADD_EBOOK_PRODUCT_ADDITIONAL_INFO: `/admin/add-ebook-product/additional-info`,
  ADD_EBOOK_PRODUCT_DETAILD_INFO: `/admin/add-ebook-product/detaild-info`,
  ADD_EBOOK_PRODUCT_MEDIA: `/admin/add-ebook-product/product-media`,
  ADD_ARTICLE_PRODUCT: `/admin/add-article-product`,
  ADD_ARTICLE_PRODUCT_ADDITIONAL_INFO: `/admin/add-article-product/additional-info`,
  ADD_ARTICLE_PRODUCT_DETAILD_INFO: `/admin/add-article-product/detaild-info`,
  ADD_ARTICLE_PRODUCT_MEDIA: `/admin/add-article-product/product-media`,

};

export const PublicRoutes = [AppRoutes.LOGIN, AppRoutes.REGISTER];
